### ISSUE TITLE
help with config.json

### ISSUE THREAD

**Issue by reesepushkin** [x0-h/Schemata-Bot#2]
Getting the error message, chrome launches Spotify and stays on home screen, no login.
Login credentials email/pwd are correct.
No proxy mode.
No output to discord bot so the error may be with the login process or proxy.

Any chance you might know the error?

Thank you 🙏

<img width="454" alt="Screenshot 2023-06-01 at 12 47 07 PM" src="https://github.com/x0-h/Schemata-Bot/assets/112848346/9994c1d4-b6c8-4d09-bf30-f650466d601f">

**Comment by reesepushkin** [comment]
Problem seems to be with login credentials, but triple checked they are correct.
Maybe there is something else wrong?

**Comment by reesepushkin** [comment]
Able to bypass the accepting cookies part of `Schemata.py` which achieves the login:
<img width="874" alt="Screenshot 2023-06-01 at 1 34 14 PM" src="https://github.com/x0-h/Schemata-Bot/assets/112848346/f3af0398-c762-4eb3-93b5-049ffb87e0d4">

Able to navigate to random album page.

Needed to define the XPath for the spotify repeat & play buttons:
<img width="1128" alt="Screenshot 2023-06-01 at 4 31 26 PM" src="https://github.com/x0-h/Schemata-Bot/assets/112848346/7fe590c6-9ce6-47da-b4b5-70b5a55bcf9c">

**Comment by x0-h** [comment]
Sorry for the late answer... Glad you found a way to fix your problem. Indeed, XPath is not reliable on a long period of time (I was pretty dumb back then :/...) I would recommend to swap to CSS selector if you encounter the same problem in the future !
